wevtutil sl "Microsoft-Windows-DNS-Client/Operational" /e:true
wevtutil sl "Microsoft-Windows-Diagnostics-Performance/Operational" /e:true
wevtutil sl "Microsoft-Windows-Kernel-Boot" /e:true
wevtutil sl "Microsoft-Windows-Kernel-General" /e:true
wevtutil sl "Microsoft-Windows-DeviceSetupManager/Admin" /e:true
wevtutil sl "Microsoft-Windows-DeviceSetupManager/Operational" /e:true
wevtutil sl "Microsoft-Windows-BitLocker-DrivePreparationTool/Operational" /e:true
wevtutil sl "Microsoft-Windows-WindowsUpdateClient/Operational" /e:true
wevtutil sl "Microsoft-Windows-DNS-Server/Operational" /e:true
